version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_tripmate
    environment:
      MYSQL_ROOT_PASSWORD: narephat_929541741
      MYSQL_DATABASE: tripmate_app
    ports:
      - "3307:3306"   # <<--- ด้านซ้ายคือ port ของเครื่อง, ด้านขวาคือ port ภายใน container
    volumes:
      - ./mysql_data:/var/lib/mysql   # เก็บข้อมูลไว้ในเครื่องเรา (ไม่หายเวลา restart)
